### ISSUE TITLE
Feedback on page "New APIs in Java 19"

### ISSUE THREAD

**Issue by xzel23** [marchof/java-almanac#131]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/jdk/19/apidiff/18/):

The page reports that the following methods were added to CompletableFuture in Java 19:
 - exceptionNow
 - resultNow
 - state

But these have been added to the interface Future instead. The links to the documentation also point to the wrong page (the one about CompletableFuture, should be Futur).

**Comment by marchof** [comment]
Hi @xzel23,

the API comparison is based on the actual class files. Probably CompletableFuture implements these methods therefore they show in the report. I know that these situations may lead to dead links, but we're currently not considering the type hierarchy. See also #4
