### ISSUE TITLE
How are api diffs made?

### ISSUE THREAD

**Issue by bowbahdoe** [marchof/java-almanac#141]
Just a curiosity that isn't clear from first read. How are the api diffs generated? Is it manual or is there a tool that could be used for other libraries?

**Comment by marchof** [comment]
Hi @bowbahdoe, it is automatically created based in the Java class files. I use the [ASM](https://asm.ow2.io/) library for this. The tool itself is not open sources because it is very specific for OpenJDK and I don't want to maintain a general purpose tool.

**Comment by bowbahdoe** [comment]
I'm trying to make a general purpose tool, so I might loop back with questions then 😅

**Comment by marchof** [comment]
@bowbahdoe I added you to the repository which does the job in the background. Please feel free to pick any ideas.
