### ISSUE TITLE
Feedback on page "JDK Features"

### ISSUE THREAD

**Issue by jkmcl** [marchof/java-almanac#167]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/features/): Make the list of features sortable by the Release column. When upgrading from Java 11 to 17 for example, it is easier to see which features were introduced between these two releases if the features could be sorted by release.

**Comment by marchof** [comment]
This page only lists the features where we have articles about. Maybe this should be stated here.

Indeed new features are only listed for each release separately, like for [Java 17](https://javaalmanac.io/jdk/17/). We don't have a list of all features yet. That would be a nice enhancement.

**Comment by marchof** [comment]
Now there is a list with all features. Thanks for pointing out this idea!
