### ISSUE TITLE
Feedback on page "The Java Version Almanac"

### ISSUE THREAD

**Issue by chkpnt** [marchof/java-almanac#170]
Is there a reason that the tooltip for the status REL is "Future Release" and not "Current Release"?

https://github.com/marchof/java-almanac/blob/d72a66ba856e47345df1eb8c1e40635bfc136056/site/data/jdk/status.json#L3C1-L3C1

<img width="215" alt="grafik" src="https://github.com/marchof/java-almanac/assets/1956979/ad3487bf-74e5-4f06-a8b8-a06454f75de2">

**Comment by marchof** [comment]
This is OpenJDK teminology: There are feature releases (EOL at next release) and LTS releases (support for many years).

**Comment by chkpnt** [comment]
But isn't that confusing? I (as a Java developer) find this terminology missleading, as it suggests, that only the LTS releases are supported. On the Almanac, that interpretation is reinforced by the grey background color of `.status-REL`. IMHO it should be green as well.

The people maintaining the [Wikipedia page](https://en.wikipedia.org/wiki/Java_version_history) also doesn't care about the OpenJDK terminology, they call it "latest release":
<img width="686" alt="grafik" src="https://github.com/marchof/java-almanac/assets/1956979/3d39310b-d01a-4dfe-a3f2-1a5e8fb08cbb">

**Comment by marchof** [comment]
> as it suggests, that only the LTS releases are supported

Which is kind of correct, EOL is exactly 6 month after the release (last update 4 month after release).

**Comment by chkpnt** [comment]
> > as it suggests, that only the LTS releases are supported
> 
> 
> 
> Which is kind of correct, EOL is exactly 6 month after the release (last update 4 month after release).

To be precise, isn't the decision of the support period and whether it's an LTS release or not purely up to the vendors?

**Comment by marchof** [comment]
This is correct. Java Almanac only tracks public releases from the OpenJDK project. You can get commercial updates for almost all EOL versions.
