### ISSUE TITLE
filtering packages

### ISSUE THREAD

**Issue by jirkapinkas** [marchof/java-almanac#18]
Hi, 

first I'd like to thank you very much for this tool. It's really useful. 

If you have some spare time to waste, it would be great to implement filtering of packages in UI (for example I don't really care about changes in java.awt or javax packages, IMHO it would be really useful to be able to filter them out).

Just my 2 cents.

Again thank you very much, you did a really great job already.

**Comment by FDelporte** [comment]
Please check https://foojay.io/almanac/jdk-8/ there is filtering available there based on this data. Maybe you can find the requested features already there...

**Comment by marchof** [comment]
Hi @jirkapinkas [javaalmanac.io](https://javaalmanac.io/) is statically generated from the raw data and I have to admit that I prefer this kind of simple web content.

Do you have a specific proposal how the filtering should look like and be implemented?

**Comment by jirkapinkas** [comment]
@FDelporte : foojay.io doesn't implement such functionality :-(

@marchof : IMHO it would be best to just add simple JavaScript code to implement this functionality in UI. Unfortunately since it's static HTML, AFAIK it wouldn't be possible to use hot stuff like React / Vue, but "ugly" jquery and just simple JavaScript.

For the filtering itself: It would be best to filter set of packages (effectively they would just be removed from table). The only trick would be to remove all rows that are associated with some package from the table.

**Comment by marchof** [comment]
@jirkapinkas How do you define the "set of packages"?

I'm not convinced yet and I don't think I will find time for this. Maybe you demonstrate in a pull request what exactly should be achieved?
