### ISSUE TITLE
Feedback on page "JDK Features"

### ISSUE THREAD

**Issue by perpostor** [marchof/java-almanac#192]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/features/): The list of features to be sorted in descending order based on the Java version first, then alphabetically based on the feature name. The reason is that I visit this page to look for the newest features, and I have to hunt up and down the Release column to find what I'm interested in. Generally speaking, the older the Java release is, the less interest a feature page would have, so it makes sense to keep latest releases on top.

**Comment by perpostor** [comment]
I'm on mobile, so can't raise a PR now, but did a little digging, and Hugo's [sort](https://gohugo.io/functions/collections/sort/#sort-a-map) might do the trick if applied to the features shortcode range function. Will give it a try when I have a chance.

**Comment by marchof** [comment]
@perpostor Good idea. Also all other pages here list Java versions in descending order.

**Comment by perpostor** [comment]
For some reason GH didn't link the PR, but here it is -> https://github.com/marchof/java-almanac/pull/194
