### ISSUE TITLE
Feedback on page "Java 9"

### ISSUE THREAD

**Issue by sdavids** [marchof/java-almanac#205]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/jdk/9/):

Please mention [JEP 226: UTF-8 Property Resource Bundles](https://openjdk.org/jeps/226).

`*.properties` files defaulting to UTF-8 is a big change.

No more:

.editorconfig
```
[*.properties]
charset = latin1
```

or similar configuration of source formatters.

**Comment by marchof** [comment]
@sdavids Nice catch. Thanks!
