### ISSUE TITLE
Feedback on page "Unnamed Patterns and Variables (JEP 443)"

### ISSUE THREAD

**Issue by brunobaiano** [marchof/java-almanac#218]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/features/unnamedvariables/):
update Release to Java 22, JEP 443 to JEP 456

The References section already mention JEP 443

**Comment by brunobaiano** [comment]
I added a fix here https://github.com/marchof/java-almanac/pull/221

**Comment by marchof** [comment]
Fixed in #221
