### ISSUE TITLE
Java 11 JDK end-of-life date correct?

### ISSUE THREAD

**Issue by MarkvanOsch** [marchof/java-almanac#226]
Hi, I see on the Java 11 page that the end of life is set on **oct 2024**:
https://javaalmanac.io/jdk/11/

But on the page of Adoptium I see that this Java 11 JDK (Eclipse Temurin) is expected to be available until at least **oct 2027**:
https://adoptium.net/support/#_release_roadmap

Why this mismatch in end of life dates, or am I'm misunderstanding this meaning of end of life?

**Comment by marchof** [comment]
@MarkvanOsch Thanks for the hint! The problem is that there is no official EOL date for OpenJDK releases. Every vendor can decide on its own how long public or private updates are provided. Also the number is probably outdated. I'll do some research.

**Comment by marchof** [comment]
Wikipedia has a nice overview of EOL dates of different vendors: https://en.wikipedia.org/wiki/Java_version_history

**Comment by MarkvanOsch** [comment]
@marchof I like your website with overview more, all info nice together. So I hope we can make a community effort to keep it up to date. 👌

I think for most the OSS/public end of life date is the most important. How to get that clear per JDK supplier? Or maybe the most recommended OSS JDK in the industry as adoptium/eclipse terinum at the moment.

**Comment by marchof** [comment]
@MarkvanOsch Following your proposal I updates the EOL dates with the Eclipse Temurin dates.
