### ISSUE TITLE
Feedback on page "Java 21"

### ISSUE THREAD

**Issue by vaukai** [marchof/java-almanac#240]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/jdk/21/):

Latest Version 	21.0.5

**Comment by marchof** [comment]
@vaukai Thanks for the heads-up! We use Eclipse Temurin docker images to automatically update this information along with the API diffs. Should have been updated since 3 days. I'll check what is missing.

**Comment by marchof** [comment]
Looks line [actions/setup-java](https://github.com/actions/setup-java) does not yet know about it:

![image](https://github.com/user-attachments/assets/f4416c6f-d090-49aa-b873-6a8b9475b7ae)

**Comment by marchof** [comment]
Setting

    check-latest: true

 on [actions/setup-java](https://github.com/actions/setup-java) fixed it. Thanks for reporting!
