### ISSUE TITLE
Amazon Corretto 15 exists

### ISSUE THREAD

**Issue by pthariensflame** [marchof/java-almanac#30]
Can it show up on the site, please?  ❤️

**Comment by marchof** [comment]
Sure, thanks for the hint! --> Fixed https://javaalmanac.io/jdk/15/

By any chance are you involved in the Corretto project? There are two typos on the JDK 11 download site which breaks my semi-automated update process.

**Comment by pthariensflame** [comment]
I'm not involved in it, sadly; I'm just someone who's a little obsessive about details.  XD
