### ISSUE TITLE
Diffs not accurate in some corner cases

### ISSUE THREAD

**Issue by AlanBateman** [marchof/java-almanac#4]
Just came across this project and looking at the diff reports on the github page.

It appears that non-public classes are showing up as "new", e.g. the Java SE 8 -> 11 report lists WeakPairMap classes but they are not public and should not be shown.

Non-public super classes or interfaces are showing up, e.g. java.lang.Package extends a non-public class in java.lang that is not part of the API. You don't see it in the javadoc but it is showing up in the diffs.

 Proxy.newProxyInterface is an example where the diffs suggests is no longer throw IllegalArgumentException but it hasn't changed, it still throws this exception but you need to read it in the javadoc. It might be better to ignore unchecked exceptions when doing diffs as they may or may not appear in the declaration.

There are several examples where it appears that methods have been removed but there is no source or binary compatibility issue because the methods are overrides of methods defined in a super class, e.g. the diff report suggest ECGenParameterSpec.getName has been removed but it's defined by the super class. Another example is Adler32.update(byte[]) where the method is now a default method in the interface implemented by Adler32. Not easy to convey this time of change in a diffs report.

**Comment by marchof** [comment]
@AlanBateman This is a very simple tool which simply compares class files one by one. I wrote it primarly for myself to identify areas where we get changes and have direct links to JavaDoc.

For now it does not consider type hierarchies and can therefore not check whether a change is source compatible. If you're looking for a detailed analysis you should use more sophisticated tools like [japicmp](https://github.com/siom79/japicmp). JDK reports can be found here:(https://github.com/AdoptOpenJDK/jdk-api-diff)

Anyways, thanks for the examples! I leave this ticket open and see whether I can add some improvements if I find some spare time.

**Comment by marchof** [comment]
Background info about compatibility:

* https://wiki.openjdk.java.net/display/csr/Kinds+of+Compatibility
* https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html

**Comment by marchof** [comment]
The inner classes of `WeakPairMap` are actually public in Java 11:

    $ ./java -version
    openjdk version "11.0.2" 2019-01-15
    OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
    
    $ ./javap java.lang.WeakPairMap.Pair.Lookup
    Compiled from "WeakPairMap.java"
    public final class java.lang.WeakPairMap$Pair$Lookup<K1, K2> implements java.lang.WeakPairMap$Pair<K1, K2> {
      java.lang.WeakPairMap$Pair$Lookup(K1, K2);
      public K1 first();
      public K2 second();
      public int hashCode();
      public boolean equals(java.lang.Object);
    }
    
    $ ./javap java.lang.WeakPairMap.Pair.Weak
    Compiled from "WeakPairMap.java"
    public final class java.lang.WeakPairMap$Pair$Weak<K1, K2> extends java.lang.WeakPairMap$WeakRefPeer<K1> implements java.lang.WeakPairMap$Pair<K1, K2> {
      java.lang.WeakPairMap$Pair$Weak(K1, K2, java.lang.ref.ReferenceQueue<java.lang.Object>);
      java.lang.WeakPairMap$Pair$Weak<?, ?> weakPair();
      public K1 first();
      public K2 second();
      public int hashCode();
      public boolean equals(java.lang.Object);
    }

**Comment by AlanBateman** [comment]
Does the tool look at the access flags in the InnerClasses attribute?

**Comment by marchof** [comment]
@AlanBateman No, it doesn't.
