### ISSUE TITLE
Feedback on page "Class File Versions"

### ISSUE THREAD

**Issue by daveloyall** [marchof/java-almanac#50]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/bytecode/versions/): Please describe how the "bytecode" line in `18.json` (for example) is populated.  Thank you!!

**Comment by marchof** [comment]
Hello @daveloyall,

I'm not sure whether I understand your question correctly:

- These Json files are edited manually
- The bytecode version is specified in the Java Virtual Machine Specification of every Java release
