### ISSUE TITLE
Feedback on page "Java 15": include API changes promoted from "preview"

### ISSUE THREAD

**Issue by xzel23** [marchof/java-almanac#62]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/jdk/15/):

`java.lang.String.stripIndent()` was promoted from "preview" in JDK 15. It shows up in JDK 13 where it was introduced as a preview feature. I think it would be great, to have a distinction between "preview" and "added", so ideally it would show up as "preview" in JDK 13 and then again as either "added" or "promoted" in JDK 15.

I haven't checked how the almanac works behind the scenes, but it might be possible to detect "promoted" API changes by evaluating the "@since" tag of the new version. `stripIndent()` had "@since 13" in Java 13 and 14, and "@since 15" in Java 15.

BTW: Great project!!!

**Comment by marchof** [comment]
Hi @xzel23, thanks for the idea! We use class files to calculate the diffs which should contain the `@jdk.internal.javac.PreviewFeature` annotation. Let me check how this can be integrated.

**Comment by marchof** [comment]
The `PreviewFeature` annotation mentioned above was only introduced in Java 14. In Java 13 they used comments in the Javadoc:

     * @since 13
     *
     * @deprecated  This method is associated with text blocks, a preview language feature.
     *              Text blocks and/or this method may be changed or removed in a future release.
     */
    @Deprecated(forRemoval=true, since="13")
    public String stripIndent() {

As we don't have the source code to create the API diffs we can probably not easily flag preview APIs before Java 14.

**Comment by marchof** [comment]
The diff generator now considers the `@jdk.internal.javac.PreviewFeature` annotation (only after Java 14).
