### ISSUE TITLE
Feedback on page "New APIs in Java 17"

### ISSUE THREAD

**Issue by rob-spoor** [marchof/java-almanac#64]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/jdk/17/apidiff/11/):

* Allowing parts to be collapsed (and then of course expanded). The tree can become quite large, which makes it unpleasant to scroll through.
* Filtering.

I've written something similar at https://robtimus.github.io/whats-new-in-java/, but your UI is nicer, and it includes information I didn't know how to render yet (like new implements clauses). Your site combined with https://docs.oracle.com/en/java/javase/17/docs/api/new-list.html means that I'm probably going to cease work on that.

**Comment by marchof** [comment]
See #45

**Comment by rob-spoor** [comment]
I'm closing this one, because it's an almost identical duplicate of #45.
