### ISSUE TITLE
Potential Type Problems

### ISSUE THREAD

**Issue by HenrySoftwareStudio** [marchof/java-almanac#84]
https://github.com/marchof/java-almanac/blob/3a28a7414e8586da0646f07183cb685bcf1b0f35/dataapi/src/main/java/io/javaalmanac/data/GetOperationDefinition.java#L11
Hi. At this line, with the var as type, there is a potential for a type-related error. Please explicitly list what the type is expected to be.

**Comment by marchof** [comment]
I used `var` at several places. Are you suggesting not to use it in general or what is the problem with this specific instance?

**Comment by HenrySoftwareStudio** [comment]
Just suggest avoiding it in general because this will cause people to start guessing what type is `name`.
