### ISSUE TITLE
Feedback on page "Java 16"

### ISSUE THREAD

**Issue by ksilz** [marchof/java-almanac#98]
Hello, I would like to propose the following improvement on [this page](https://javaalmanac.io/jdk/16/):

Microsoft also has a [Java 16 distribution](https://docs.microsoft.com/en-us/java/openjdk/older-releases#openjdk-16). I used the ARM version on my M1 Mac. Please add it to the page.

**Comment by marchof** [comment]
Thanks @ksilz for pointing out that there is a "older releases" page. I added this page to the collecting mechanism, here is the update of the data: 1eea90fa27cf48853e5868d1ca2308ffa7736d48
